name: article-generator

on:
  schedule:
    - cron: '0 10 * * *'  # Todos los días de la semana, excepto los domingos, a las 10 a.m.
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Reemplaza con la versión de Python que necesites

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run script with retry
      run: |
        DATE=$(date +'%Y-%m-%d')
        MAX_RETRIES=5
        RETRY_COUNT=0
        SUCCESS=false
        until [ $RETRY_COUNT -ge $MAX_RETRIES ] || [ "$SUCCESS" = true ]; do
          python main.py
          FILE_SIZE=$(stat -c%s "printed-editions/$DATE.pdf")
          if [ $FILE_SIZE -ge 1048576 ]; then
            SUCCESS=true
          else
            RETRY_COUNT=$((RETRY_COUNT+1))
            echo "File size is less than 1MB, retrying... ($RETRY_COUNT/$MAX_RETRIES)"
            sleep 10  # Espera 10 segundos antes de reintentar
          fi
        done

    - name: Commit and push if changes
      run: |
        git config --global user.email "alexcerezocontreras@gmail.com"
        git config --global user.name "alexcerezo"
        git add .
        git diff-index --quiet HEAD || git commit -m "Update articles"
        git push
