name: article-generator

on:
  schedule:
    - cron: '0 10 * * 1-6'  # Todos los días de la semana, excepto los domingos, a las 10 a.m.
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Reemplaza con la versión de Python que necesites

    - name: Install dependencies
      run: |
        pip install requests 

    - name: Run script
      run: python main.py

    - name: Commit and push if changes
      run: |
        git config --global user.email "alexcerezocontreras@gmail.com"
        git config --global user.name "alexcerezo"
        git add .
        git diff-index --quiet HEAD || git commit -m "Update articles"
        git push